using Ceng382_25_26_202311031.Data;
using Ceng382_25_26_202311031.Models;
using Ceng382_25_26_202311031.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ceng382_25_26_202311031.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SimplePdfService _pdfService;

        public OrdersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            SimplePdfService pdfService)
        {
            _context = context;
            _userManager = userManager;
            _pdfService = pdfService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var user = await _userManager.GetUserAsync(User);

            int pageSize = 5;

            var query = _context.Orders
                .Include(x => x.OrderItems)
                .Where(x => x.UserId == user!.Id);

            int totalOrders = await query.CountAsync();

            var orders = await query
                .OrderByDescending(x => x.OrderDate)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            ViewBag.CurrentPage = page;

            ViewBag.TotalPages =
                (int)Math.Ceiling(totalOrders / (double)pageSize);

            return View(orders);
        }

        public async Task<IActionResult> Receipt(int id)
        {
            var order = await GetUserOrder(id);

            if (order == null)
                return NotFound();

            var lines = new List<string>
            {
                $"Order ID: {order.Id}",
                $"Date: {order.OrderDate:dd.MM.yyyy HH:mm}",
                $"Status: {order.Status}",
                $"Total Amount: {order.TotalAmount} TL",
                "",
                "Ordered Items:"
            };

            foreach (var item in order.OrderItems)
            {
                lines.Add($"{item.MenuItemName} - {item.Quantity} x {item.FinalUnitPrice} TL = {item.Subtotal} TL");

                lines.Add($"Base Price: {item.UnitPrice} TL");

                lines.Add($"Customization Price: {item.CustomizationPrice} TL");

                lines.Add($"Customizations: {item.SelectedCustomizations}");

                lines.Add($"Caterer: {item.CatererName}");
            }

            lines.Add("");

            lines.Add("This receipt was dynamically generated by Mealinge.");

            var pdf =
                _pdfService.CreatePdf(
                    "Mealinge Order Receipt",
                    lines);

            return File(
                pdf,
                "application/pdf",
                $"receipt-order-{order.Id}.pdf");
        }

        public async Task<IActionResult> Agreement(int id)
        {
            var order = await GetUserOrder(id);

            if (order == null)
                return NotFound();

            var lines = new List<string>
            {
                $"Agreement Number: AGR-{order.Id}",
                $"Order ID: {order.Id}",
                $"Date: {order.OrderDate:dd.MM.yyyy HH:mm}",
                "",
                "This agreement confirms that the customer placed an order through Mealinge.",
                "The caterer is responsible for preparing the ordered menu items.",
                "The customer confirms the simulated payment for the selected items.",
                "",
                $"Total Agreement Amount: {order.TotalAmount} TL",
                "",
                "Order Details:"
            };

            foreach (var item in order.OrderItems)
            {
                lines.Add($"{item.MenuItemName} from {item.CatererName}");

                lines.Add($"Selected Customizations: {item.SelectedCustomizations}");

                lines.Add($"Final Item Price: {item.FinalUnitPrice} TL");
            }

            lines.Add("");

            lines.Add("This agreement PDF was generated dynamically based on order data.");

            var pdf =
                _pdfService.CreatePdf(
                    "Mealinge Customer Agreement",
                    lines);

            return File(
                pdf,
                "application/pdf",
                $"agreement-order-{order.Id}.pdf");
        }

        private async Task<Order?> GetUserOrder(int id)
        {
            var user = await _userManager.GetUserAsync(User);

            return await _context.Orders
                .Include(x => x.OrderItems)
                .FirstOrDefaultAsync(x =>
                    x.Id == id &&
                    x.UserId == user!.Id);
        }
    }
}